{% set name = "meta" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bagari/meta/archive/refs/heads/main.tar.gz
  sha256: dd351c3d31111538e033753d2219f66c0c3a2163805f9a10f8f83e90ea21a44f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - python {{ python }}
    - pip
    - git
    - setuptools
    - boost =1.78
    - itk ==5.3.0
    - libitk ==5.3.0
    - libitk-devel ==5.3.0
    # - hdf5 >=1.12,<1.13
    - hdf5 >=1.12.2,<1.14.1.0a0
    - vtk >=9.2.6,<9.3 build=*{{ build_variant }}*
    - zlib
    - eigen >=3.2
    - libtiff >=4.0

  host:
    - qhull
    - boost =1.78
    - itk ==5.3.0
    - libitk ==5.3.0
    - libitk-devel ==5.3.0
    # - hdf5 >=1.12,<1.13
    - hdf5 >=1.12.2,<1.14.1.0a0
    - vtk >=9.2.6,<9.3 build=*{{ build_variant }}*
    - zlib
    - eigen >=3.2
    - libtiff >=4.0 
    - python {{ python }}
    # - glew  # [build_variant == "qt"]
    - libxml2
    - libtheora
    - libogg
    - jsoncpp
    - gl2ps
    - libpng
    - libnetcdf
    - pugixml >=1.11.4,<1.12.0a0
    - sqlite
    - proj >=9.1.1,<9.1.2.0a0
    - freetype
    - expat
    - double-conversion
    - lz4-c
    - libjpeg-turbo
    - tbb
    - fftw     
  run:
    - qhull
    - boost =1.78
    - itk ==5.3.0
    - libitk ==5.3.0
    - libitk-devel ==5.3.0
    # - hdf5 >=1.12,<1.13
    - hdf5 >=1.12.2,<1.14.1.0a0
    - vtk >=9.2.6,<9.3 build=*{{ build_variant }}*
    - zlib
    - eigen >=3.2
    - libtiff >=4.0 
    - python {{ python }}
    - numpy
    - setuptools
    - nibabel
    - pandas
    - pyvista
    - scipy
    - tqdm
    - tslearn
    - dipy
    # - glew  # [build_variant == "qt"]
    - libxml2
    - libtheora
    - libogg
    - jsoncpp
    - gl2ps
    - libpng
    - libnetcdf
    - pugixml >=1.11.4,<1.12.0a0
    - sqlite
    - proj >=9.1.1,<9.1.2.0a0
    - freetype
    - expat
    - double-conversion
    - lz4-c
    - libjpeg-turbo
    - tbb
    - fftw    

test:
  imports:
    - meta
  commands:
    - meta --help

about:
  home: https://github.com/bagari/meta
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Medial Tractography Analysis (MeTA)'
  description: |
    MeTA is a workflow implemented to minimize microstructural heterogeneity 
    in diffusion MRI (dMRI) metrics by extracting and parcellating the core 
    volume along the bundle length in the voxel-space directly while effectively 
    preserving bundle shape and efficiently capturing the regional variation 
    within and along white matter (WM) bundles.

extra:
  recipe-maintainers:
    - bagari
