{% set name = "meta" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/bagari/meta.git
  git_rev: 1.0.0

channels:
  - conda-forge
  - defaults

build:
  number: 0
  skip: true  # [not (linux-64 or osx-64)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - boost =1.78
    - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*  # [linux]
    - vtk =9.2  # [osx]
    - hdf5 =1.12
    - itk =5.3
    - libitk =5.3
    - libitk-devel =5.3
    - zlib
    - eigen >=3.2
    - libtiff >=4.0
    - python =3.9
    - pip
    - git    

  host:
    - boost =1.78
    - eigen >=3.2
    - libtiff >=4.0
    - zlib
    - qhull
    - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*  # [linux]
    - vtk =9.2  # [osx]
    - hdf5 =1.12
    - itk =5.3
    - libitk =5.3
    - libitk-devel =5.3
    - python =3.9
    - pip
    - git

  run:
    - boost =1.78
    - eigen >=3.2
    - libtiff >=4.0
    - zlib
    - qhull
    - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*  # [linux]
    - vtk =9.2  # [osx]
    - hdf5 =1.12
    - itk =5.3
    - libitk =5.3
    - libitk-devel =5.3
    - python =3.9
    - pip
    - git
    - numpy
    - nibabel
    - pandas
    - pyvista
    - scipy
    - tqdm
    - tslearn
    - dipy

test:
  commands:
    - python -c "import meta; print('Meta imported successfully')"
    - meta --help

about:
  home: https://github.com/bagari/meta
  summary: 'Medial Tractography Analysis (MeTA)'
  description: |
    MeTA is a workflow implemented to minimize microstructural heterogeneity 
    in diffusion MRI (dMRI) metrics by extracting and parcellating the core 
    volume along the bundle length in the voxel-space directly while effectively 
    preserving bundle shape and efficiently capturing the regional variation 
    within and along white matter (WM) bundles.

extra:
  recipe-maintainers:
    - bagari
