{% set name = "meta" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bagari/meta/archive/refs/heads/main.tar.gz
  sha256: 05b63af36db742a0b9027fc322426e38c4b83f996a9c4d34045baf4b936b9ebc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - python {{ python }}
    - pip
    - git
    - setuptools
    - boost =1.82
    - itk ==5.3.0
    - libitk ==5.3.0
    - libitk-devel ==5.3.0
    - hdf5 >=1.14.2,<1.14.3.0a0
    - vtk-base >=9.2.6,<9.3.0 build=*{{ build_variant }}*
    - libexpat <2.6
    - libexpat >=2.5.0,<3.0a0
    - vtk-io-ffmpeg >=9.2.6,<9.3.0 build=*{{ build_variant }}*

  host:
    - qhull
    - boost =1.82
    - itk ==5.3.0
    - libitk ==5.3.0
    - libitk-devel ==5.3.0
    - hdf5 >=1.14.2,<1.14.3.0a0
    - vtk-base >=9.2.6,<9.3.0 build=*{{ build_variant }}*
    - python {{ python }}
    - libexpat <2.6
    - libexpat >=2.5.0,<3.0a0
    - vtk-io-ffmpeg >=9.2.6,<9.3.0 build=*{{ build_variant }}*

  run:
    - qhull
    - boost =1.82
    - itk ==5.3.0
    - libitk ==5.3.0
    - libitk-devel ==5.3.0
    - hdf5 >=1.14.2,<1.14.3.0a0
    - vtk-base >=9.2.6,<9.3.0 build=*{{ build_variant }}*
    - python {{ python }}
    - numpy
    - setuptools
    - nibabel
    - pandas
    - pyvista
    - scipy
    - tqdm
    - tslearn
    - dipy
    - libexpat <2.6
    - libexpat >=2.5.0,<3.0a0
    - vtk-io-ffmpeg >=9.2.6,<9.3.0 build=*{{ build_variant }}*

test:
  imports:
    - meta
  commands:
    # - meta --help
    # - cmrep_vskel -h
    - set -x
    - echo "Testing meta"
    - meta --help
    - echo "Testing cmrep_vskel"
    - cmrep_vskel -h || true
    - echo "cmrep_vskel exited with code $?"
    - echo "Testing vtklevelset"
    - which vtklevelset || echo "vtklevelset not found"
    - ls -l $(which vtklevelset) || echo "Cannot list vtklevelset"
    - vtklevelset -h || echo "vtklevelset failed with exit code $?"

about:
  home: https://github.com/bagari/meta
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Medial Tractography Analysis (MeTA)'
  description: |
    MeTA is a workflow implemented to minimize microstructural heterogeneity 
    in diffusion MRI (dMRI) metrics by extracting and parcellating the core 
    volume along the bundle length in the voxel-space directly while effectively 
    preserving bundle shape and efficiently capturing the regional variation 
    within and along white matter (WM) bundles.

extra:
  recipe-maintainers:
    - bagari
