{% set name = "meta" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bagari/meta/archive/refs/tags/v1.0.0.tar.gz
  sha256: 87986191f06795cf493017dadf1313d7b505b95407f07b2255e9981612d4940f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - libboost-devel >=1.82
    - libboost-python-devel
    - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*
    - hdf5 >=1.12,<1.13
    - itk =5.3
    - libitk =5.3
    - libitk-devel =5.3
    - zlib
    - eigen >=3.2
    - libtiff >=4.0
    - python {{ python }}
    - setuptools
    - pip
    - git

  host:
    - libboost-devel >=1.82
    - libboost-python-devel
    - eigen >=3.2
    - libtiff >=4.0
    - zlib
    - qhull
    - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*
    - hdf5 >=1.12,<1.13
    - itk =5.3
    - libitk =5.3
    - libitk-devel =5.3
    - python {{ python }}

  run:
    - eigen >=3.2
    - libtiff >=4.0
    - zlib
    - qhull
    - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*
    - hdf5 >=1.12,<1.13
    - itk =5.3
    - libitk =5.3
    - libitk-devel =5.3
    - python {{ python }}
    - numpy
    - nibabel
    - pandas
    - pyvista
    - scipy
    - tqdm
    - tslearn
    - dipy

test:
  imports:
    - meta
  commands:
    - meta --help

about:
  home: https://github.com/bagari/meta
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Medial Tractography Analysis (MeTA)'
  description: |
    MeTA is a workflow implemented to minimize microstructural heterogeneity 
    in diffusion MRI (dMRI) metrics by extracting and parcellating the core 
    volume along the bundle length in the voxel-space directly while effectively 
    preserving bundle shape and efficiently capturing the regional variation 
    within and along white matter (WM) bundles.

extra:
  recipe-maintainers:
    - bagari
