{% set name = "meta" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bagari/meta/archive/refs/heads/main.tar.gz
  sha256: 1a8699a92883c8452f7d16d7905f67fdf248d1d6e87c0e0ab2f5d2dcfe28c93d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - python {{ python }}
    - pip
    - git
    - setuptools
    - boost =1.78
    # - itk =5.3
    - libitk ==5.4.0
    - libitk-devel ==5.4.0
    - hdf5 >=1.14.2,<1.14.3.0a0
    # - hdf5 >=1.12.2,<1.14.1.0a0
    # - vtk >=9.2,<9.3 build=*{{ build_variant }}*
    - vtk-base >=9.2.6,<9.3.0 build=*{{ build_variant }}*
    # - zlib
    # - eigen
    # - libtiff >=4.5.0,<4.6.0a0
    - libexpat <2.6
    - libexpat >=2.5.0,<3.0a0
    # - vtk-io-ffmpeg >=9.3.0,<9.3.1 build=*{{ build_variant }}*

  host:
    - qhull
    - boost =1.78
    # - itk =5.3
    - libitk ==5.4.0
    - libitk-devel ==5.4.0
    - hdf5 >=1.14.2,<1.14.3.0a0
    # - hdf5 >=1.12.2,<1.14.1.0a0
    # - vtk >=9.2,<9.3 build=*{{ build_variant }}*
    - vtk-base >=9.2.6,<9.3.0 build=*{{ build_variant }}*
    # - zlib
    # - eigen
    # - libtiff >=4.5.0,<4.6.0a0
    - python {{ python }}
    # - libxml2
    # - libtheora
    # - libogg
    # - jsoncpp
    # - gl2ps
    # - libpng
    # - libnetcdf >=4.9.1,<4.9.3.0a0
    # - pugixml >=1.11.4,<1.12.0a0
    # - sqlite
    # - proj >=9.1.1,<9.1.2.0a0
    # - freetype
    # - expat
    # - double-conversion
    # - lz4-c
    # - libjpeg-turbo >=2.1.5.1,<3.0a0
    # - tbb
    # - fftw
    # - icu
    # - libzip
    # - hdf4
    # - zstd
    # - bzip2
    # - libcurl
    - libexpat <2.6
    - libexpat >=2.5.0,<3.0a0
    # - xz
    # - glew  # [build_variant == "qt"]
    # - qt-main  # [build_variant == "qt"]
    # - mesalib >=21.0,<24
    # - vtk-io-ffmpeg >=9.3.0,<9.3.1 build=*{{ build_variant }}*

  run:
    # - {{ stdlib("c") }}
    - qhull
    - boost =1.78
    # - itk =5.3
    - libitk ==5.4.0
    - libitk-devel ==5.4.0
    - hdf5 >=1.14.2,<1.14.3.0a0
    # - hdf5 >=1.12.2,<1.14.1.0a0
    # - vtk >=9.2,<9.3 build=*{{ build_variant }}*
    - vtk-base >=9.2.6,<9.3.0 build=*{{ build_variant }}*
    # - zlib
    # - eigen
    # - libtiff >=4.5.0,<4.6.0a0 
    - python {{ python }}
    - numpy
    - setuptools
    - nibabel
    - pandas
    - pyvista
    - scipy
    - tqdm
    - tslearn
    - dipy
    # - libxml2
    # - libtheora
    # - libogg
    # - jsoncpp
    # - gl2ps
    # - libpng
    # - libnetcdf >=4.9.1,<4.9.3.0a0
    # - pugixml >=1.11.4,<1.12.0a0
    # - sqlite
    # - proj >=9.1.1,<9.1.2.0a0
    # - freetype
    # - expat
    # - double-conversion
    # - lz4-c
    # - libjpeg-turbo >=2.1.5.1,<3.0a0
    # - tbb
    # - fftw
    # - icu
    # - libzip
    # - hdf4
    # - zstd
    # - bzip2
    # - libcurl
    - libexpat <2.6
    - libexpat >=2.5.0,<3.0a0
    # - xz
    # - glew  # [build_variant == "qt"]
    # - qt-main  # [build_variant == "qt"]
    # - mesalib >=21.0,<24
    # - vtk-io-ffmpeg >=9.3.0,<9.3.1 build=*{{ build_variant }}*

test:
  imports:
    - meta
  commands:
    - meta --help

about:
  home: https://github.com/bagari/meta
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Medial Tractography Analysis (MeTA)'
  description: |
    MeTA is a workflow implemented to minimize microstructural heterogeneity 
    in diffusion MRI (dMRI) metrics by extracting and parcellating the core 
    volume along the bundle length in the voxel-space directly while effectively 
    preserving bundle shape and efficiently capturing the regional variation 
    within and along white matter (WM) bundles.

extra:
  recipe-maintainers:
    - bagari
