{% set name = "meta" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bagari/meta/archive/refs/heads/main.tar.gz
  sha256: dd351c3d31111538e033753d2219f66c0c3a2163805f9a10f8f83e90ea21a44f

channels:
  - conda-forge
  - defaults
channel_priority: strict

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - python {{ python }}
    - pip
    - git
    - setuptools
    - boost =1.78
    # - itk =5.3
    - itk {{ pin_compatible('itk', max_pin='5.3') }}
    # - libitk =5.3
    - libitk {{ pin_compatible('libitk', max_pin='5.3') }}
    # - libitk-devel =5.3
    - libitk-devel {{ pin_compatible('libitk-devel', max_pin='5.3') }}
    - hdf5 >=1.12,<1.13
    # - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*
    - vtk {{ pin_compatible('vtk', max_pin='9.2') }} build=*{{ vtk_backend }}*
    - mesalib >=21.0,<24  # [build_variant == "osmesa"]
    - zlib
    - eigen >=3.2
    - libtiff >=4.0

  host:
    - boost =1.78
    - qhull
    # - itk =5.3
    - itk {{ pin_compatible('itk', max_pin='5.3') }}
    # - libitk =5.3
    - libitk {{ pin_compatible('libitk', max_pin='5.3') }}
    # - libitk-devel =5.3
    - libitk-devel {{ pin_compatible('libitk-devel', max_pin='5.3') }}
    - hdf5 >=1.12,<1.13
    # - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*
    - vtk {{ pin_compatible('vtk', max_pin='9.2') }} build=*{{ vtk_backend }}*
    - mesalib >=21.0,<24  # [build_variant == "osmesa"]
    - zlib
    - eigen >=3.2
    - libtiff >=4.0 
    - python {{ python }}
    
  run:
    - qhull
    - itk =5.3
    - libitk =5.3
    - libitk-devel =5.3
    - hdf5 >=1.12,<1.13
    - vtk >=9.2,<9.3 build=*{{ vtk_backend }}*
    - mesalib >=21.0,<24  # [build_variant == "osmesa"]
    - zlib
    - eigen >=3.2
    - libtiff >=4.0 
    - python {{ python }}
    - numpy
    - setuptools
    - nibabel
    - pandas
    - pyvista
    - scipy
    - tqdm
    - tslearn
    - dipy

test:
  imports:
    - meta
  commands:
    - meta --help

about:
  home: https://github.com/bagari/meta
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Medial Tractography Analysis (MeTA)'
  description: |
    MeTA is a workflow implemented to minimize microstructural heterogeneity 
    in diffusion MRI (dMRI) metrics by extracting and parcellating the core 
    volume along the bundle length in the voxel-space directly while effectively 
    preserving bundle shape and efficiently capturing the regional variation 
    within and along white matter (WM) bundles.

extra:
  recipe-maintainers:
    - bagari
